busko_journey_homepage:
    pattern:  /index
    defaults: { _controller: BuskoJourneyBundle:Home:index }
    
busko_journey_Timetablehomepage:
    pattern:  /timetableHome
    defaults: { _controller: BuskoJourneyBundle:TimetableHome:Timetable }
