parameters:
#    busko_journey.example.class: Busko\JourneyBundle\Example

services:
#    busko_journey.example:
#        class: %busko_journey.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
