busko_homepage:
    pattern:  /home
    defaults: { _controller: BuskoJourneyBundle:Home:index }
 
BuskoEntityBundle_assistants:
       resource: "@BuskoEmployeeBundle/Resources/config/routing/assistants.yml"
       prefix:   /assistants
       
BuskoEntityBundle_drivers:
        resource: "@BuskoEmployeeBundle/Resources/config/routing/drivers.yml"
        prefix:   /drivers