parameters:
#    busko_employee.example.class: Busko\EmployeeBundle\Example

services:
#    busko_employee.example:
#        class: %busko_employee.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
