parameters:
#    busko_message.example.class: Busko\MessageBundle\Example

services:
#    busko_message.example:
#        class: %busko_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
