parameters:
#    busko_branch.example.class: Busko\BranchBundle\Example

services:
#    busko_branch.example:
#        class: %busko_branch.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
