parameters:
#    busko_bus.example.class: Busko\BusBundle\Example

services:
#    busko_bus.example:
#        class: %busko_bus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
